# This workflow will publish a docker image for every full release to the GitHub package repository

name: Create Docker Image (Release and Staging)

on:
  release:
    types: [published]
  push:
    branches:
      - release
    tags:
      - v*

env:
  REPO: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set lowercase repo name
        run: |
          echo "IMAGE_NAME=${REPO,,}" >> ${GITHUB_ENV}

      - name: Checkout 
        uses: actions/checkout@v4.1.2

      - name: Read version from package.json
        id: package_version
        run: |
          VERSION=$(jq -r .version < package.json)
          echo "PACKAGE_VERSION=v${VERSION}" >> ${GITHUB_ENV}
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Extract metadata (tags, labels) for the image
        uses: docker/metadata-action@v5.5.1
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.PACKAGE_VERSION  }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          file: Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
